name: "format code"

# run on pull requests to develop
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      # check out HEAD on the branch
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2
          file_pattern: 'Classes/*'
      # format the latest commit
      - name: format code
        uses: purduesigbots/clang-format-action@main
      # commit the changes
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🎨 apply clang-format changes
          branch: ${{ github.head_ref }}