name: "format code"

# run on pull requests to develop
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2
      # format the latest commit
      - name: Format code
        uses: purduesigbots/clang-format-action@main
        with:
          style: file
      # commit the changes
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🎨 apply clang-format changes
          branch: ${{ github.head_ref }}
