name: clang-format Code Formatter

# run on pull requests to develop
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: clang-format Code Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Clang Code Formatter
        uses: antoinealb/clang-format-action@clang9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
